apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-slt-services.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-slt-services.labels" . | indent 4 }}
    component:  {{ template "ska-oso-slt-services.name" . }}
    domain: environment
    function: ska-oso-slt-services-environment
    intent: production
data:
  KUBE_NAMESPACE: {{ .Release.Namespace }}
  ODA_BACKEND_TYPE: {{ .Values.rest.oda.backendType }}
  POSTGRES_HOST: {{ if .Values.rest.oda.postgres.host }} {{ .Values.rest.oda.postgres.host }} {{ else }} {{ .Release.Name }}-postgresql {{ end }}
  ADMIN_POSTGRES_PASSWORD: {{ .Values.rest.oda.postgres.password }}
  {{ if .Values.rest.oda.postgres.port }}
  POSTGRES_PORT: {{ .Values.rest.oda.postgres.port | quote }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.db.name }}
  POSTGRES_DB_NAME: {{ .Values.rest.oda.postgres.db.name }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.user }}
  ADMIN_POSTGRES_USER: {{ .Values.rest.oda.postgres.user }}
  {{ end }}

